<?php
require_once '../Model/Product.php';

$products = Product::Select();
?>

<br />
<div class="card-columns">
    <?php
    while ($product = $products->fetch_assoc())
    {
    ?>
        <div class="card">
            <div class="card-block">
                <h4 class="card-title"><?=$product['name']?></h4>
                <p class="card-text">R$<?=$product['value']?></p>
                <a id="buy-product" class="btn btn-primary" href="#">Adicionar à lista de compras</a>
                <p class="card-text"><small class="text-muted">Ultima atualização: <?=$product['updated_at']?></small></p>
            </div>
        </div>
    <?php
    }
    ?>
</div>
