<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="UTF-8">
    <title>Trabalho</title>

    <!--BOOTSTRAP-->
    <link rel="stylesheet" href="public/css/bootstrap.min.css" type="text/css" />
</head>
<body>

    <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse sticky-top">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a id="home" class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a id="products" class="nav-link" href="#">Products</a>
                </li>
                <li class="nav-item">
                    <a id="profile" class="nav-link" href="#">Profile</a>
                </li>
            </ul>
<!--            <form class="form-inline my-2 my-lg-0">-->
<!--                <input class="form-control mr-sm-2" type="text" placeholder="Search">-->
<!--                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>-->
<!--            </form>-->
        </div>
    </nav>

    <div class="container" id="main-container">

    </div>

    <!--SCRIPTS-->
    <script src="public/js/jquery-3.2.1.min.js"></script>
    <script src="public/js/tether.min.js"></script>
    <script src="public/js/bootstrap.min.js"></script>
    <script src="public/js/base.js"></script>
</body>
</html>